server:
  port: 8762
spring:
  application:
    name: servicehi
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client: #客户端注册进eureka服务列表内
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #是否映射IP，访问路径时会显示IP
info:
  app.name: servicehi
  company.name: www.ze.com
  build.artifactId: servicehi
  build.version: 0.0.1
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
